lab-1/Project/Models/Антиквариат.cs
namespace DBK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Антиквариат
    {
        public int СколькоЛет { get; set; }

        [StringLength(50)]
        public string Происхождение { get; set; }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        public virtual Товар Товар { get; set; }
    }
}

lab-1/Project/Controllers/АнтиквариатController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DBK.Models;

namespace DBK.Controllers
{
    public class АнтиквариатController : Controller
    {
        private Model db = new Model();

        // GET: Антиквариат
        public ActionResult Index()
        {
            var антиквариат = db.Антиквариат.Include(а => а.Товар);
            return View(антиквариат.ToList());
        }


        [HttpPost]
        public ActionResult IndexFilterPlaceAge(string place, int? age)
        {
            var антиквариат = db.Антиквариат.Include(а => а.Товар).Where(a => a.СколькоЛет == age).Where(a => a.Происхождение == place);
            return View("Index", антиквариат.ToList());
        }

        // GET: Антиквариат/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Антиквариат антиквариат = db.Антиквариат.Find(id);
            if (антиквариат == null)
            {
                return HttpNotFound();
            }
            return View(антиквариат);
        }

        // GET: Антиквариат/Create
        public ActionResult Create()
        {
            ViewBag.id = new SelectList(db.Товар, "id", "id");
            return View();
        }

        // POST: Антиквариат/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,СколькоЛет,Происхождение")] Антиквариат антиквариат)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Антиквариат.Add(антиквариат);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.id = new SelectList(db.Товар, "id", "id", антиквариат.id);
                return View(антиквариат);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
        }

        // GET: Антиквариат/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Антиквариат антиквариат = db.Антиквариат.Find(id);
            if (антиквариат == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = new SelectList(db.Товар, "id", "id", антиквариат.id);
            return View(антиквариат);
        }

        // POST: Антиквариат/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,СколькоЛет,Происхождение")] Антиквариат антиквариат)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(антиквариат).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.id = new SelectList(db.Товар, "id", "id", антиквариат.id);
                return View(антиквариат);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Антиквариат/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Антиквариат антиквариат = db.Антиквариат.Find(id);
            if (антиквариат == null)
            {
                return HttpNotFound();
            }
            return View(антиквариат);
        }

        // POST: Антиквариат/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Антиквариат антиквариат = db.Антиквариат.Find(id);
                db.Антиквариат.Remove(антиквариат);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

lab-1/Project/Views/Антиквариат/Create.cshtml
@model DBK.Models.Антиквариат

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Антиквариат</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, "id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.СколькоЛет, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.СколькоЛет, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.СколькоЛет, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Происхождение, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Происхождение, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Происхождение, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab-1/Project/Views/Антиквариат/Delete.cshtml
@model DBK.Models.Антиквариат

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Антиквариат</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Товар.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Товар.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.СколькоЛет)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.СколькоЛет)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Происхождение)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Происхождение)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

lab-1/Project/Views/Антиквариат/Details.cshtml
@model DBK.Models.Антиквариат

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Антиквариат</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Товар.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Товар.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.СколькоЛет)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.СколькоЛет)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Происхождение)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Происхождение)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

lab-1/Project/Views/Антиквариат/Edit.cshtml
@model DBK.Models.Антиквариат

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Антиквариат</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.СколькоЛет, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.СколькоЛет, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.СколькоЛет, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Происхождение, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Происхождение, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Происхождение, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab-1/Project/Views/Антиквариат/Index.cshtml
@model IEnumerable<DBK.Models.Антиквариат>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("IndexFilterPlaceAge", "Антиквариат", FormMethod.Post))
{
    <input name="place" placeholder="place">
    <input name="age" placeholder="age">
    <input type="submit" />
}



@if (Request.Cookies["logged_as"]?.Value != "ProductOwner")
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Товар.Название)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.СколькоЛет)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Происхождение)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Товар.Название)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.СколькоЛет)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Происхождение)
            </td>
            <td>
                @if (Request.Cookies["logged_as"]?.Value != "ProductOwner")
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.id });
                    @: |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id });
                    @: |
                }
                @Html.ActionLink("Details", "Details", new { id = item.id })
            </td>
        </tr>
    }

</table>