lab-1/Project/Models/Электроника.cs
namespace DBK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Электроника
    {
        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        public int Вольтаж { get; set; }

        [Required]
        [StringLength(50)]
        public string Производитель { get; set; }

        [StringLength(50)]
        public string Модель { get; set; }

        public virtual Товар Товар { get; set; }
    }
}

lab-1/Project/Controllers/ЭлектроникаController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DBK.Models;

namespace DBK.Controllers
{
    public class ЭлектроникаController : Controller
    {
        private Model db = new Model();

        // GET: Электроника
        public ActionResult Index()
        {
            var электроника = db.Электроника.Include(э => э.Товар);
            return View(электроника.ToList());
        }

        [HttpPost]
        public ActionResult IndexFilterManufacVolt(int? Вольтаж, string Производитель)
        {
            var электроника = db.Электроника.Include(э => э.Товар).Where(e => e.Вольтаж == Вольтаж).Where(e => e.Производитель == Производитель);
            return View("Index", электроника.ToList());
        }

        // GET: Электроника/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Электроника электроника = db.Электроника.Find(id);
            if (электроника == null)
            {
                return HttpNotFound();
            }
            return View(электроника);
        }

        // GET: Электроника/Create
        public ActionResult Create()
        {
            ViewBag.id = new SelectList(db.Товар, "id", "Название");
            return View();
        }

        // POST: Электроника/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Вольтаж,Производитель,Модель")] Электроника электроника)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Электроника.Add(электроника);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.id = new SelectList(db.Товар, "id", "Название", электроника.id);
                return View(электроника);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Электроника/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Электроника электроника = db.Электроника.Find(id);
            if (электроника == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = new SelectList(db.Товар, "id", "Название", электроника.id);
            return View(электроника);
        }

        // POST: Электроника/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Вольтаж,Производитель,Модель")] Электроника электроника)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(электроника).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.id = new SelectList(db.Товар, "id", "Название", электроника.id);
                return View(электроника);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Электроника/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Электроника электроника = db.Электроника.Find(id);
            if (электроника == null)
            {
                return HttpNotFound();
            }
            return View(электроника);
        }

        // POST: Электроника/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Электроника электроника = db.Электроника.Find(id);
                db.Электроника.Remove(электроника);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

lab-1/Project/Views/Электроника/Create.cshtml
@model DBK.Models.Электроника

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Электроника</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, "id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Вольтаж, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Вольтаж, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Вольтаж, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Производитель, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Производитель, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Производитель, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Модель, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Модель, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Модель, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab-1/Project/Views/Электроника/Delete.cshtml
@model DBK.Models.Электроника

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Электроника</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Товар.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Товар.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Вольтаж)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Вольтаж)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Производитель)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Производитель)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Модель)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Модель)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

lab-1/Project/Views/Электроника/Details.cshtml
@model DBK.Models.Электроника

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Электроника</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Товар.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Товар.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Вольтаж)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Вольтаж)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Производитель)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Производитель)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Модель)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Модель)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

lab-1/Project/Views/Электроника/Edit.cshtml
@model DBK.Models.Электроника

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Электроника</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Вольтаж, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Вольтаж, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Вольтаж, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Производитель, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Производитель, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Производитель, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Модель, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Модель, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Модель, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab-1/Project/Views/Электроника/Index.cshtml
@model IEnumerable<DBK.Models.Электроника>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("IndexFilterManufacVolt", "Электроника", FormMethod.Post))
{
    <input name="Вольтаж" placeholder="Вольтаж">
    <input name="Производитель" placeholder="Производитель">
    <input type="submit" />
}


@if (Request.Cookies["logged_as"]?.Value != "ProductOwner")
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Товар.Название)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Вольтаж)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Производитель)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Модель)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Товар.Название)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Вольтаж)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Производитель)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Модель)
            </td>
            <td>
                @if (Request.Cookies["logged_as"]?.Value != "ProductOwner")
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.id });
                    @: |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id });
                    @: |
                }
                @Html.ActionLink("Details", "Details", new { id = item.id })
            </td>
        </tr>
    }

</table>