lab-1/Project/Models/Товар.cs
namespace DBK.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;
    using System.Data.Entity.Spatial;

    public partial class Товар
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Товар()
        {
            Продажа = new HashSet<Продажа>();
        }

        [DatabaseGenerated(DatabaseGeneratedOption.None)]
        public int id { get; set; }

        [Required]
        [StringLength(50)]
        public string Название { get; set; }

        [Column(TypeName = "money")]
        public decimal Цена { get; set; }

        [StringLength(300)]
        public string Описание { get; set; }

        public double Состояние { get; set; }

        [Display(Name = "Владелец ID")]
        public int Владелец_id { get; set; }

        public DateTime? ДатаСдачи { get; set; }

        public int? ПроцентМагазина { get; set; }

        public bool? ВыкупаетЛиМагазин { get; set; }

        public virtual Антиквариат Антиквариат { get; set; }

        public virtual Владелец Владелец { get; set; }

        public virtual Другое Другое { get; set; }

        public virtual Одежда Одежда { get; set; }

        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Продажа> Продажа { get; set; }

        public virtual Электроника Электроника { get; set; }
    }
}

lab-1/Project/Controllers/ТоварController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using DBK.Models;

namespace DBK.Controllers
{
    public class ТоварController : Controller
    {
        private Model db = new Model();

        // GET: Товар
        public ActionResult Index()
        {
            var товар = db.Товар.Include(т => т.Антиквариат).Include(т => т.Владелец).Include(т => т.Другое).Include(т => т.Одежда).Include(т => т.Электроника);
            return View(товар.ToList());
        }

        [HttpPost]
        public ActionResult IndexFindId(int? product_id)
        {
            var товар = db.Товар.Include(т => т.Антиквариат).Include(т => т.Владелец).Include(т => т.Другое).Include(т => т.Одежда).Include(т => т.Электроника).Where(t => t.id == product_id);
            return View("Index", товар.ToList());
        }

        // GET: Товар/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Товар товар = db.Товар.Find(id);
            if (товар == null)
            {
                return HttpNotFound();
            }
            return View(товар);
        }

        // GET: Товар/Create
        public ActionResult Create()
        {
            ViewBag.id = new SelectList(db.Антиквариат, "id", "Происхождение");
            ViewBag.Владелец_id = new SelectList(db.Владелец, "id", "id");
            ViewBag.id = new SelectList(db.Другое, "id", "СвойТип");
            ViewBag.id = new SelectList(db.Одежда, "id", "Размер");
            ViewBag.id = new SelectList(db.Электроника, "id", "Производитель");
            return View();
        }

        // POST: Товар/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "id,Название,Цена,Описание,Состояние,Владелец_id,ДатаСдачи,ПроцентМагазина,ВыкупаетЛиМагазин")] Товар товар)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Товар.Add(товар);
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }

                ViewBag.id = new SelectList(db.Антиквариат, "id", "Происхождение", товар.id);
                ViewBag.Владелец_id = new SelectList(db.Владелец, "id", "id", товар.Владелец_id);
                ViewBag.id = new SelectList(db.Другое, "id", "СвойТип", товар.id);
                ViewBag.id = new SelectList(db.Одежда, "id", "Размер", товар.id);
                ViewBag.id = new SelectList(db.Электроника, "id", "Производитель", товар.id);
                return View(товар);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Товар/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Товар товар = db.Товар.Find(id);
            if (товар == null)
            {
                return HttpNotFound();
            }
            ViewBag.id = new SelectList(db.Антиквариат, "id", "Происхождение", товар.id);
            ViewBag.Владелец_id = new SelectList(db.Владелец, "id", "id", товар.Владелец_id);
            ViewBag.id = new SelectList(db.Другое, "id", "СвойТип", товар.id);
            ViewBag.id = new SelectList(db.Одежда, "id", "Размер", товар.id);
            ViewBag.id = new SelectList(db.Электроника, "id", "Производитель", товар.id);
            return View(товар);
        }

        // POST: Товар/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "id,Название,Цена,Описание,Состояние,Владелец_id,ДатаСдачи,ПроцентМагазина,ВыкупаетЛиМагазин")] Товар товар)
        {
            try
            {
                if (ModelState.IsValid)
                {
                    db.Entry(товар).State = EntityState.Modified;
                    db.SaveChanges();
                    return RedirectToAction("Index");
                }
                ViewBag.id = new SelectList(db.Антиквариат, "id", "Происхождение", товар.id);
                ViewBag.Владелец_id = new SelectList(db.Владелец, "id", "id", товар.Владелец_id);
                ViewBag.id = new SelectList(db.Другое, "id", "СвойТип", товар.id);
                ViewBag.id = new SelectList(db.Одежда, "id", "Размер", товар.id);
                ViewBag.id = new SelectList(db.Электроника, "id", "Производитель", товар.id);
                return View(товар);
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        // GET: Товар/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Товар товар = db.Товар.Find(id);
            if (товар == null)
            {
                return HttpNotFound();
            }
            return View(товар);
        }

        // POST: Товар/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            try
            {
                Товар товар = db.Товар.Find(id);
                db.Товар.Remove(товар);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

lab-1/Project/Views/Товар/Create.cshtml
@model DBK.Models.Товар

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Товар</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.id, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.id, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Название, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Название, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Название, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Цена, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Цена, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Цена, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Описание, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Описание, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Описание, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Состояние, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Состояние, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Состояние, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Владелец_id, "Владелец_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Владелец_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Владелец_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ДатаСдачи, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ДатаСдачи, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ДатаСдачи, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ПроцентМагазина, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ПроцентМагазина, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ПроцентМагазина, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ВыкупаетЛиМагазин, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.DropDownListFor(model => model.ВыкупаетЛиМагазин, new[]
                       {
                        new SelectListItem() { Value = bool.FalseString, Text = "НЕ выкупает", Selected = true },
                        new SelectListItem() { Value = bool.TrueString, Text = "Выкупает" }
                       })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab-1/Project/Views/Товар/Delete.cshtml
@model DBK.Models.Товар

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Товар</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Антиквариат.Происхождение)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Антиквариат.Происхождение)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Владелец.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Владелец.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Другое.СвойТип)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Другое.СвойТип)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Одежда.Размер)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Одежда.Размер)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Электроника.Производитель)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Электроника.Производитель)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Цена)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Цена)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Описание)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Описание)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Состояние)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Состояние)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ДатаСдачи)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ДатаСдачи)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ПроцентМагазина)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ПроцентМагазина)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ВыкупаетЛиМагазин)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ВыкупаетЛиМагазин)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

lab-1/Project/Views/Товар/Details.cshtml
@model DBK.Models.Товар

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Товар</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Антиквариат.Происхождение)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Антиквариат.Происхождение)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Владелец.id)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Владелец.id)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Другое.СвойТип)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Другое.СвойТип)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Одежда.Размер)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Одежда.Размер)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Электроника.Производитель)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Электроника.Производитель)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Название)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Название)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Цена)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Цена)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Описание)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Описание)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Состояние)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Состояние)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ДатаСдачи)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ДатаСдачи)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ПроцентМагазина)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ПроцентМагазина)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ВыкупаетЛиМагазин)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ВыкупаетЛиМагазин)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Edit", "Edit", new { id = Model.id }) |
    @Html.ActionLink("Back to List", "Index")
</p>

lab-1/Project/Views/Товар/Edit.cshtml
@model DBK.Models.Товар

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Товар</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.id)

        <div class="form-group">
            @Html.LabelFor(model => model.Название, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Название, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Название, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Цена, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Цена, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Цена, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Описание, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Описание, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Описание, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Состояние, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Состояние, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Состояние, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Владелец_id, "Владелец_id", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("Владелец_id", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.Владелец_id, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ДатаСдачи, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ДатаСдачи, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ДатаСдачи, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ПроцентМагазина, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ПроцентМагазина, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ПроцентМагазина, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ВыкупаетЛиМагазин, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <div class="checkbox">
                    @Html.EditorFor(model => model.ВыкупаетЛиМагазин)
                    @Html.ValidationMessageFor(model => model.ВыкупаетЛиМагазин, "", new { @class = "text-danger" })
                </div>
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

lab-1/Project/Views/Товар/Index.cshtml
@model IEnumerable<DBK.Models.Товар>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>


@using (Html.BeginForm("IndexFindId", "Товар", FormMethod.Post))
{
    <input name="product_id" placeholder="product ID">
    <input type="submit" />
}

@if (Request.Cookies["logged_as"]?.Value != "ProductOwner")
{
    <p>
        @Html.ActionLink("Create New", "Create")
    </p>
}
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Антиквариат.Происхождение)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Владелец.id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Другое.СвойТип)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Одежда.Размер)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Электроника.Производитель)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Название)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Цена)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Описание)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Состояние)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ДатаСдачи)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ПроцентМагазина)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ВыкупаетЛиМагазин)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Антиквариат.Происхождение)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Владелец.id)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Другое.СвойТип)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Одежда.Размер)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Электроника.Производитель)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Название)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Цена)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Описание)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Состояние)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ДатаСдачи)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ПроцентМагазина)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ВыкупаетЛиМагазин)
            </td>
            <td>
                @if (Request.Cookies["logged_as"]?.Value != "ProductOwner")
                {
                    @Html.ActionLink("Edit", "Edit", new { id = item.id });
                    @: |
                    @Html.ActionLink("Delete", "Delete", new { id = item.id });
                    @: |
                }
                @Html.ActionLink("Details", "Details", new { id = item.id })
            </td>
        </tr>
    }

</table>